### ISSUE TITLE
[BUG] Potential Recurrent IPPO Bug

### ISSUE THREAD

**Issue by EdanToledo** [instadeepai/Mava#1006]
### Describe the bug
Its possible there is a slight error in the resetting of hidden states for IPPO. Instead of using the done flag to reset, it would be simpler and ensure correctness to use the timestep.first() flag to reset the hidden state. I've linked below a picture of a rware tiny-2ag run using the fix and using the current develop branch. Although both are increasing there is roughly a 100% or 2x performance at each interval point.

Below is the Actor Mean Return:
![Screenshot 2024-02-07 at 11 24 49](https://github.com/instadeepai/Mava/assets/42650996/26be3674-1064-4c9d-a700-be4eeeb274a5)

Below is the Evaluator Mean Return:
![Screenshot 2024-02-07 at 11 26 06](https://github.com/instadeepai/Mava/assets/42650996/6fcd3078-a22f-4635-b4a0-bc3505f98362)

Although this could be variance, nothing was changed between the experiments besides the fix. I've pushed the branch that ran the orange line experiment and it is called fix/recurrent-ppo. This would be a worthwhile investigation.

**Comment by RuanJohn** [comment]
A [link to the branch](https://github.com/instadeepai/Mava/tree/fix/recurrent-ppo) with this fix.

**Comment by RuanJohn** [comment]
An update on this, the suggested fix uses `timestep.first()` to reset the hidden states, but since no timestep will ever be a `timestep.first()` when using Jumanji's auto reset wrapper the hidden states were just never getting reset. 
Not ever resetting the hidden states does lead to far better performance for the recurrent systems though so this is a whole other question to consider in itself.

**Comment by sash-a** [comment]
Bug was fixed in #1076
