### ISSUE TITLE
SMAC API Support is redundant

### ISSUE THREAD

**Issue by jkterry1** [instadeepai/Mava#297]
If you guys didn't see, SMAC added full support for the PettingZoo API, so you don't have to support it separately anymore.

**Comment by KaleabTessera** [comment]
Hi @jkterry1 , thanks for the heads up. :raised_hands:  We were excited when we saw Smac has PZ support! Nice @rodrigodelazcano ! 

We had a look at the wrapper and had some questions relating to some parts of it (for example, why have a `max_cycles` var, when Smac maps have a `limit` param for each map, etc ). Not sure where to ask those questions?

**Comment by jkterry1** [comment]
@rodrigodelazcano can answer them here

**Comment by rodrigodelazcano** [comment]
Hi Kaleab! Sorry for the late reply and thank you for your kind interest in this new feature for SMAC. I’ll be happy to answer all of your questions.

1. As you mentioned, `limit` in SMAC is a fixed parameter for each map. `max_cycles` is a user defined argument that mostly every PZ native environment has. The `max_cycles` allows for the users to actually choose a variable limit of steps per episode as for their needs. For example you can initialize an environment as follows:
    ```
    env = StarCraft2PZEnv.env(map_name="3m", max_cycles=10)
    ```
      This will start an environment with a limit number of steps per episode of 10, instead of the fixed limit of 60 defined in the SMAC map `3m`. (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/starcraft2/maps/smac_maps.py#L20)
      If you wish to keep using the default `limit` parameter in SMAC you can just set to `True` the usual SMAC argument `continuing_episode` as follows:
    ```
    env = StarCraft2PZEnv.env(map_name="3m", continuing_episode=True)
    ```
2. PZ takes care of dead agents not in the same way as SMAC. In the action space for each agent in SMAC an action no-op is reserved for dead agents (always action `0`). Only dead agents can take this action and not alive ones (https://github.com/oxwhirl/smac/blob/master/docs/smac.md#action-space). This is reflected in the action mask of the observation of each agent in SMAC.
On the other hand, PZ eliminates the dead agent from the agent list that you iterate through in each episode (https://github.com/PettingZoo-Team/PettingZoo/blob/20d06b9baef67ca76b70f1b8b14ef670149e9052/pettingzoo/utils/env.py#L137). This means that no action is required in a PZ environment for dead agents and `action 0` (no-op) will be redundant. This is the reason why one action is removed from the action space in PZ since `action 0` will always be assigned to dead agents (done) (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/pettingzoo/StarCraft2PZEnv.py#L170).
With PZ you will be using the action space with a range from 0:max(action_space -1). This actions will then be internally displaced by 1 so that `action 0` can be reserved for dead agents.
3. Here we are following the PZ naming convention for agents. The integer added after each agents type is not its `agent_id`, its a counting of the number of agents of that type. For example, in the `MMM` map the list of agents will look as follows:
    ```
    ['marauder_0', 'marauder_1', 'marine_0', 'marine_1', 'marine_2', 'marine_3', 'marine_4', 'marine_5', 'marine_6', 'medivac_0']
    ```
    As you can see the last integer of the agent naming is the counting of that type of agent which restarts from `0` for every new agent. This is the reason for `last_type`, to trigger the reset of the counting to `0` for a change in agent type.
4. As previously mentioned, the list of agents in PZ only includes live agents. In `_observe_all`, we iterate through the list of live agents and only extract their observation. Dead agents observations are not relevant.
5. This question I don't understand what you mean exactly. Can you clarify?

Thank you for all of your questions Kaleab. I hope this helps and if you have any more questions don't hesitate to ask.

**Comment by KaleabTessera** [comment]
Thanks @rodrigodelazcano for your detailed replies. Here are my responses, with a few more questions. 
1. Thanks, that makes sense. 
2. I understand. Handling the done agents this way has proven to be tricky in the parallel env, for the following reasons:
- 2.1 `self.agents` is actually always a step behind since it is updated before the step (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/pettingzoo/StarCraft2PZEnv.py#L164)  and not after like in other PZ envs (https://github.com/PettingZoo-Team/PettingZoo/blob/f410be89bd33fc95a4e2773bf727cdc3156e1b7e/pettingzoo/utils/conversions.py#L91). If this is fixed, it means we have the latest `self.agents` when calling `step`. I happy to make a PR moving updating self.agents to after this line (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/pettingzoo/StarCraft2PZEnv.py#L180), if you agree? 
- 2.2 Handling done agents, **but** still alive is quite tricky. This happens for example when the episode limit is reached, but the agent is still alive. If the agent is done, and you pass a none action, then that none gets converted to a zero action (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/pettingzoo/StarCraft2PZEnv.py#L170). When trying the zero action on the smac env, it fails since the unit still has health but we are trying to take a no-op (error - `AssertionError: Agent 0 cannot perform action 0`). How do handle done agents, who are still alive? What actions get passed? Even if you don't pass an action for those agents, since it defaults to zero (https://github.com/oxwhirl/smac/blob/371df71ab1b6248f49287dc9e961dd9c5735c12b/smac/env/pettingzoo/StarCraft2PZEnv.py#L163), you still get the error above.
3. Thanks for the clarification.
4. This `_observe_all` is not only for live agents due to point 2.1 (`self.agents` is always one step behind). 
5. Nvm sorry, it is not a valid question.

**Comment by benblack769** [comment]
2. I recognize that this is a continual problem with the parallel env interface that is a significant burden to the developer. I will try to see what can be done about it.

**Comment by benblack769** [comment]
2.2 Can you figure something out here @rodrigodelazcano? This doesn't seem necessary. When the end of episode is reached, all agents should be done, and no more agents should take actions after that. If that is not the case, then please comment here: https://github.com/PettingZoo-Team/PettingZoo/issues/464

**Comment by KaleabTessera** [comment]
@benblack769 Thanks for your feedback. 
@rodrigodelazcano @benblack769 So changing this: 
``` 
 def step(self, all_actions):
        action_list = [0] * self.env.n_agents
        self.agents = [agent for agent in self.agents if not self.all_dones[agent]]
        for agent in self.possible_agents:
            agent_id = self.get_agent_smac_id(agent)
            if agent in all_actions:
                if all_actions[agent] is None:
                    action_list[agent_id] = 0
                else:
                    action_list[agent_id] = all_actions[agent] + 1
        self._reward, terminated, smac_info = self.env.step(action_list)
        self.frames += 1
        done = terminated or self.frames >= self.max_cycles

        all_infos = {agent: {} for agent in self.agents}
        # all_infos.update(smac_info)
        all_dones = self._all_dones(done)
        self.agents = [agent for agent in self.agents if not all_dones[agent]]
        all_rewards = self._all_rewards(self._reward)
        all_observes = self._observe_all()

        self.all_dones = all_dones

        return all_observes, all_rewards, all_dones, all_infos
```
To this (moved self.agents to use the latest dones):
```
def step(self, all_actions):
        action_list = [0] * self.env.n_agents
        for agent in self.possible_agents:
            agent_id = self.get_agent_smac_id(agent)
            if agent in all_actions:
                if all_actions[agent] is None:
                    action_list[agent_id] = 0
                else:
                    action_list[agent_id] = all_actions[agent] + 1
        self._reward, terminated, smac_info = self.env.step(action_list)
        self.frames += 1
        done = terminated or self.frames >= self.max_cycles

        all_infos = {agent: {} for agent in self.agents}
        # all_infos.update(smac_info)
        all_dones = self._all_dones(done)
        self.agents = [agent for agent in self.agents if not all_dones[agent]]
        all_rewards = self._all_rewards(self._reward)
        all_observes = self._observe_all()

        self.all_dones = all_dones

        return all_observes, all_rewards, all_dones, all_infos
```
Fixes 2.1 and 4, and 2.2 is no longer needed since self.agents is accurate and we can stop before something like 2.2 happens. 

Does this look like a reasonable fix?

**Comment by KaleabTessera** [comment]
Another question, if I remember correctly, PZ used to overwrite the `getattr` method for some env classes, so that you could do `self._environment.[property]` as opposed to `self._environment._environment[property]`. Is that still a thing? In this case of Smac wrapper, I want to access the `.get_state()` and `get_stats()` of the underlying smac environment. Was there a reason the overwriting of `getattr` was removed (if it was removed)?

**Comment by benblack769** [comment]
The code changes look reasonable at first glance. Unfortunately, these changes will have to move slowly because I will also have to go into pettingzoo and make all these changes for the current pettingzoo environments, wrappers and tests (a necessary change that should have probably happened some time ago, but will slow things down).

As for looking at base environment methods, PZ has an `unwrapped` attribute that returns the base environment underneath the wrappers. So I belive you can access `env.unwrapped.env.get_stats()`. Is this good enough for your purposes?

**Comment by KaleabTessera** [comment]
@benblack769 I don't think you will need to update PZ, it seems to only be an issue on the SMAC wrapper (https://github.com/oxwhirl/smac/pull/81) and not other PZ wrappers. 

Thanks, I will have a look at the `unwrapped` method.

**Comment by benblack769** [comment]
No, it is definitely an issue with all the PZ wrappers. You might not have encountered the issue in other environments, but it is definitely there. 

The main thing that needs to get done before the SMAC wrapper should be changed is the tests checking that the wrapper correctly implements the API.

**Comment by jkterry1** [comment]
@KaleabTessera We pushed a new release of PettingZoo with the described fixes to the parallel api, and got a PR merged into SMAC which uses the updated version of pettingzoo and fixes the other issues with SMAC. This issue should be accomplishable now?

**Comment by KaleabTessera** [comment]
Thanks for the heads up @jkterry1 and (& PZ team) for the smac wrapper fixes! We are currently just benchmarking the pz smac wrapper with our old smac wrapper. Once we have the results and everything looks good, we will move over :)

**Comment by KaleabTessera** [comment]
Thanks @benblack769 @jkterry1 @rodrigodelazcano ! We have merged this in and are using the PZ Smac wrapper now :)
