### ISSUE TITLE
Custom policy, mapping policies, parameter sharing

### ISSUE THREAD

**Issue by KiloNovemberDelta** [instadeepai/Mava#309]
Hello everyone,

Firstly, I would like to thank you for this open source initiative, it looks promising!

I haven't found any forum to discuss, so I ask several questions regarding this library here (let me know if I have to ask elsewhere):

1) Is it possible to implement a custom policy, which is not meant to be trained, like RLLIB does through the use of "policies", "policy_mapping" and "policies_to_train" (e.g. a random policy : https://github.com/ray-project/ray/blob/master/rllib/examples/policy/random_policy.py) ?
2) I have an interest of using two policies, for two types of agent. I saw, for example at the MAPPO algorithm, the "agent_net_keys" attribute : https://github.com/instadeepai/Mava/blob/cbdbf6a90a3750428f29cc5e893ad67b54d6cee8/mava/systems/tf/mappo/builder.py#L44
But I don't know how to use it, and I haven't found any code example or documentation regarding this possibility. Do you have a minimalist code?
3) Does Mava able to train several agent, but they share the same policy (parameter sharing). The learning is centralized, while the execution is decentralized / distributed?
4) Finally, is there a way to export the tensorflow model from the checkpoint to use it outside the Mava environment? I'm not a tensorflow expert, but I don't find any .meta file on the checkpoint folder (like it is proposed here : https://gist.github.com/zhanwenchen/d628ef70e9f76525fd47d6213c30730d). Is there a way to create it? 

I deeply thank you in advance for your reading and answers!

**Comment by DriesSmit** [comment]
Hey @KiloNovemberDelta. Thanks for all your questions. I will do my best to try and respond to all of them.

1.) At the moment all the agents need to be executing a policy that gets sent to the trainer. So currently if you want to add a fixed agent you will have to wrap the environment. Therefore Mava only sees the agents with policies that should be trained on. This is what I currently do I my own work using Mava. The environment wrapper then internal handles the actions of the fixed agents. But I understand that this is not ideal. I have therefore added the request to support fixed algorithms and even policies of multiple algorithms (MAPPO + MADQN) to our Mava wishlist.

2.) Yes I can definitely share a code example depending on what you are interested in. Do you want to use e.g. MAPPO with two different network policies (e.g. `"network_1"`, `"network_2"`)? Here you can simply specify the two agents' networks by specifying e.g.: `agent_net_keys={"agent_1": "network_1", "agent_2": "network_2"}` when you are creating your system.

3.) Shared weights is an option Mava. By using agent_net_keys you can specify what networks each agent uses. So if each agent in the environment is pointing to the same network e.g. "network_1", then they are sharing the same policy. Otherwise you always just set the `shared_weights` argument in the system to true. This will automatically make all the agent share their weights. We also do support centralised training with decentralised execution. With centralised training, we e.g. provide the option for the critic to take in observations and actions from all the agents at training time. The policies still remain decentralised and only act on their local observations. 
4.) I am not sure about exporting the model that is stored inside the checkpoint. I have reached out about this issue in our internal group. @KaleabTessera @arnupretorius Any thoughts here?

**Comment by KiloNovemberDelta** [comment]
Thank you for this detailed answers, it is quit clear!
Regarding the question 4, I'm used to export the model (with Rllib) to evaluate the trained policy and compare it with other method using some evaluation criteria, which differ from rewards (e.g. how long agents take to complete the mission). Do you have a way in mind to perform this evaluation with Mava?

**Comment by KaleabTessera** [comment]
Hi @KiloNovemberDelta , thanks for your questions! 

Just to add some minor points to @DriesSmit  great reply:
1. You could implement a custom policy like make_custom_network in https://github.com/instadeepai/Mava/blob/develop/examples/quickstart.ipynb , and then set all layers to not trainable like this : 
``` 
for layer in policy_network._layers:
      layer.trainable = False
```
It will still be send to our trainer, but I think the weights will be fixed. Not sure if that meets your use-case? 

4. We `tf2_savers.Checkpointer` to automatically checkpoint and load our models and other saved state data. To export the model to tensorflow, you would need to load the checkpoint, get the model and then use tensorflow save model . 
Here is a possible example: 
```
from mava.systems.tf import savers as tf2_savers
import tensorflow as tf
import sonnet as snt

# Original  network config, e.g.
policy_network = snt.Sequential([
        snt.Linear(output_size=100),
        tf.nn.relu
])
# Check saved name of the policy used when saving checkpoint e.g. https://github.com/instadeepai/Mava/blob/cbdbf6a90a3750428f29cc5e893ad67b54d6cee8/mava/systems/tf/maddpg/training.py#L200  
checkpointer = tf2_savers.Checkpointer( objects_to_save={'policy':policy_network},directory=directory)
checkpointer.restore()
 
# Tensorflow save model - following https://github.com/deepmind/sonnet#tensorflow-saved-model 
policy_network.all_variables = list(policy_network.variables)
tf.saved_model.save(policy_network, save_location)

**Comment by KiloNovemberDelta** [comment]
Hello @KaleabTessera , thank you for this answer! 
1) It is an interesting point, however I have an interest to have a custom "formal" policy, written by hand, and not neural network trained policy. Because I'm using PettingZoo, I'm looking for a way to write this formal policy only for a certain type of agent A, while the other type of agent B are trained. I can try to write the behavior of the agent A directly in the PettingZoo environment, even if it doesn't look really nice. 
4. Great, thank you for this code! I will experiment it and let you know if I succeed to make it works!

**Comment by KaleabTessera** [comment]
@KiloNovemberDelta Just to add to point 1. If you still want implement this custom "formal" policy,  outside of the environment, you could probably just implement this a class that has a `__call__` method like this:

```
class FormalPolicy:
    def __init__(
        self,
        ...
    ):
         ....
     
    def __call__(self, inputs: tf.Tensor) -> tf.Tensor:
        # do some policy stuff - not necessarily a neural network 
        action = ...
        return action
 ```
 , then in a custom network function (e.g. `make_custom_network` in https://github.com/instadeepai/Mava/blob/develop/examples/quickstart.ipynb)  return `policies: {"agent_0": NormalNeuralNet, "agent_1": FormalPolicy}`.
