### ISSUE TITLE
[INVESTIGATION] Logging metrics

### ISSUE THREAD

**Issue by davidedomini** [instadeepai/Mava#642]
### Logging metrics

As written in the "Logging" section of the main read.me the most straightforward metrics to keep track of in order to see whether agents are learning are:
* MeanEpisodeReturn
* MeanEpisodeLength

May you provide a longer explanation of what these metrics represent and how we can interpret them to understand whether agents are learning?
There are other interesting metrics ?

**Comment by RuanJohn** [comment]
Hi @davidedomini, thank you for reaching out :) 

To answer your first question: 
* `MeanEpisodeReturn` refers to the mean over the returns obtained by each agent for a given episode. We can make use of this value to infer whether, collectively, the agents are learning since the overarching goal of the agents would be to maximize their returns over time.
* `MeanEpisodeLength` refers the mean of the episode lengths over all the agents. This metric can be interpreted in different ways depending on the environment. Some examples to consider could be that it shows us that agents are solving a problem faster (when returns remain constant but episode length decreases) or that agents are taking longer to lose at a particular game (when returns remain constant but episode length increases). 

Collectively then, these two metrics give us a nice high level overview of how our agents are learning. 

To answer your second question:
Yes, by default we log quite a few metrics in Mava at both the process and agent level. 
Some examples include: 
* At the executor and evaluator level:
    *  `StdEpisodeReturn`: The standard deviation of the episode return, which can give us an indication of how stable agent learning is
    * `MeanStepsPerSecond`: The mean steps per second taken by agents in the environment, which can give us an indication of how fast our system is acting in the environment. 
* At the trainer level:
    * `TrainerSteps`: The number or training iterations performed on the networks. 
    * `Agent0CriticLoss`: The loss of the critic network for agent 0. 
    * `Agent1PolicyLoss`: The loss of the policy network for agent 1. 

Please do not hesitate to let me know if you have any other questions :)

**Comment by DriesSmit** [comment]
Closing all TF issues as we are depreciating our TF systems.
