### ISSUE TITLE
Unable to train Mava's IPPO system on a gymnax environment.

### ISSUE THREAD

**Issue by Ziksby** [instadeepai/Mava#858]
Hi everyone,

I am attempting to create a wrapper for the [gymnax ](https://github.com/RobertTLange/gymnax)CartPole environment so that Mava's IPPO system can train on it. I was able to write the wrapper class for the CartPole environment and build the system, but I am unable to train the system due to an error that I am unsure how to fix.

I had initially attempted to train the system on Google colab, but noticed that the TensorBoard event files were not being written to. Google colab does not show the reasons why the TensorBoard files were not being written to.

As a result, I decided to train it on my local machine to detect the errors. I ran it on my local machine and the error that appears can be found [here](https://drive.google.com/file/d/16np5_qBjJ5ohjmSHf1ohcgcuBybQwMJc/view?usp=sharing). The notebook where I coded the system can be found [here](https://colab.research.google.com/drive/1NvyZBD7vq2uITxkWU9IKzd8fKqz1NZ2S?usp=sharing). Screenshots of the error can also be found at the end of the notebook.

I would be very grateful if anyone could offer any advice on how I might approach fixing this problem.

**Comment by DriesSmit** [comment]
Hi @Ziksby :slightly_smiling_face: This error is due to table signature not matching up with the data being pushed by the adders. This is normally some array type issue. As you can see in the message, one of the variables that are being pushed is of type int32. However, the adder expects the variable to be of type int64. It seems to be the action output. Maybe just take a look at your code to try and determine why the action output is of type int32 in your example, but not in the other examples.

**Comment by KaleabTessera** [comment]
Just to add to  @DriesSmit 's excellent advice, you can check `action_spec` and `observation_spec` and make sure it matches the action type in your step function. If it doesn't you can check the spec type or just cast the action in your spec.
